# Generated by Django 2.2.10 on 2021-01-28 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_componente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('requerimientos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Ingrese la categoria de estado', max_length=200)),
                ('requerimientos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('funcion', models.CharField(max_length=500)),
                ('referencia', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_muestreo', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=100, null=True)),
                ('corriente', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_medicion', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('exactitud', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente_Estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventario', models.IntegerField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion_uso', models.CharField(blank=True, max_length=100, null=True)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_componente')),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('sitio', models.CharField(blank=True, max_length=4000, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion', models.CharField(blank=True, max_length=4000, null=True)),
                ('fecha_inicio_registro', models.CharField(blank=True, max_length=2000, null=True)),
                ('sensores', models.CharField(blank=True, max_length=4000, null=True)),
                ('componentes', models.ManyToManyField(help_text='Seleccione los componentes de la estación', to='api.Componente_Estacion')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_componente')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('abreviatura', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor_Estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente_Estacion')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_sensor')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sensor')),
                ('ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion')),
            ],
        ),
        migrations.AddField(
            model_name='componente_estacion',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion'),
        ),
    ]
