# Generated by Django 2.2.10 on 2021-01-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_componente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('requerimientos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('requerimientos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(max_length=500)),
                ('funcion', models.CharField(max_length=500)),
                ('referencia', models.CharField(max_length=500)),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('numero_inventario', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=4000, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_muestreo', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion_uso', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.IntegerField()),
                ('sensor', models.CharField(blank=True, max_length=100, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=100, null=True)),
                ('corriente', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_medicion', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('exactitud', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_estacion', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('altura', models.FloatField(blank=True, null=True)),
                ('sitio', models.CharField(blank=True, max_length=4000, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=4000, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion', models.CharField(blank=True, max_length=4000, null=True)),
                ('estado', models.IntegerField()),
                ('fecha_inicio_registro', models.CharField(blank=True, max_length=2000, null=True)),
                ('equipos', models.CharField(blank=True, max_length=4000, null=True)),
                ('sensores', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
