# Generated by Django 2.2.10 on 2021-01-27 18:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=500)),
                ('funcion', models.CharField(max_length=500)),
                ('referencia', models.CharField(max_length=500)),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True)),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_muestreo', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_calibracion', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia_mantenimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor', models.CharField(blank=True, max_length=100, null=True)),
                ('voltaje', models.CharField(blank=True, max_length=100, null=True)),
                ('corriente', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_medicion', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_operacion', models.CharField(blank=True, max_length=100, null=True)),
                ('exactitud', models.CharField(blank=True, max_length=100, null=True)),
                ('resolucion', models.CharField(blank=True, max_length=100, null=True)),
                ('protocolo_comunicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Componente_Estacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este sensor particular de cada estacion', primary_key=True, serialize=False)),
                ('serial', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_inventario', models.IntegerField(blank=True, null=True)),
                ('estacion', models.CharField(blank=True, max_length=200, null=True)),
                ('protocolo_comunicacion_uso', models.CharField(blank=True, max_length=100, null=True)),
                ('componente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_componente')),
            ],
        ),
        migrations.DeleteModel(
            name='Componentes',
        ),
        migrations.AlterField(
            model_name='categoria_sensor',
            name='categoria',
            field=models.CharField(help_text='Ingrese la categoria de estado', max_length=200),
        ),
    ]
