# Generated by Django 2.2.10 on 2021-01-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210128_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_componente',
            name='color',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria_sensor',
            name='color',
            field=models.CharField(default='HOLA', max_length=100),
            preserve_default=False,
        ),
    ]
