# Generated by Django 2.2.10 on 2021-01-27 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210127_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente_estacion',
            name='estacion',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='equipos',
        ),
        migrations.AddField(
            model_name='componente_estacion',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='componentes',
            field=models.ManyToManyField(help_text='Seleccione los componentes de la estación', to='api.Componente_Estacion'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_sensor'),
        ),
    ]
