# Generated by Django 2.2.10 on 2021-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210128_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estacion',
            name='sensores',
        ),
        migrations.AddField(
            model_name='estacion',
            name='sensores',
            field=models.ManyToManyField(help_text='Seleccione los sensores de la estación', to='api.Sensor_Estacion'),
        ),
    ]
