# Generated by Django 2.2.10 on 2021-01-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210128_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='frecuencia_muestreo',
        ),
        migrations.AddField(
            model_name='componente_estacion',
            name='frecuencia_muestreo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='componente',
            name='protocolo_comunicacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
