# Generated by Django 2.2.10 on 2021-01-28 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210128_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente_estacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion'),
        ),
    ]
