# Generated by Django 2.2.10 on 2021-01-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210128_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente_estacion',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente'),
        ),
        migrations.AlterField(
            model_name='componente_estacion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_componente'),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_componente'),
        ),
        migrations.AlterField(
            model_name='sensor_estacion',
            name='componente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente_Estacion'),
        ),
        migrations.AlterField(
            model_name='sensor_estacion',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Categoria_sensor'),
        ),
        migrations.AlterField(
            model_name='sensor_estacion',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor_estacion',
            name='ubicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion'),
        ),
    ]
