# Generated by Django 2.2.10 on 2021-01-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210128_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='fecha_inicio_registro',
            field=models.DateTimeField(blank=True, max_length=2000, null=True),
        ),
    ]
