# Generated by Django 2.2.10 on 2021-02-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210129_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='unidad',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
