# Generated by Django 2.2.10 on 2021-02-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sensor_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_componente',
            name='simbolo',
            field=models.CharField(default='x', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoria_sensor',
            name='simbolo',
            field=models.CharField(default='sdakm', max_length=100),
            preserve_default=False,
        ),
    ]
