# Generated by Django 2.2.10 on 2021-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210201_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componente_estacion',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='componente_estacion',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
