# Generated by Django 2.2.10 on 2021-02-01 18:04

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210201_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente_estacion',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.models.componentes_directorio_ruta),
        ),
    ]
