# Generated by Django 2.2.10 on 2021-02-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210201_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente_estacion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='sensor_estacion',
            name='observaciones',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
