# Generated by Django 2.2.10 on 2021-02-03 14:19

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210203_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente_estacion',
            old_name='upload',
            new_name='foto',
        ),
        migrations.AddField(
            model_name='componente',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to=apps.api.models.datasheet_directorio_ruta),
        ),
    ]
