# Generated by Django 2.2.10 on 2021-02-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210203_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor_estacion',
            options={'ordering': ['id']},
        ),
    ]
