# Generated by Django 2.2.10 on 2021-02-04 18:04

import apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210203_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='estacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=apps.api.models.estaciones_directorio_ruta),
        ),
    ]
