# Generated by Django 2.2.10 on 2021-02-10 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210204_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=4000, null=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
