# Generated by Django 2.2.10 on 2021-02-11 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ingrese el nombre completo del investigador', max_length=200)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=4000, null=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion')),
                ('investigadores', models.ManyToManyField(blank=True, help_text='Seleccione los investigadores', null=True, to='api.Investigador')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tipo_Salida_De_Campo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de salida de campo', max_length=200)),
                ('color', models.CharField(max_length=100)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.AddField(
            model_name='salidas_de_campo',
            name='tipo_de_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo'),
        ),
    ]
