# Generated by Django 2.2.10 on 2021-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210211_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_salida_de_campo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
