# Generated by Django 2.2.10 on 2021-02-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210211_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidas_de_campo',
            old_name='investigadores',
            new_name='operarios',
        ),
    ]
