# Generated by Django 2.2.10 on 2021-02-16 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210211_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidas_de_campo',
            name='observaciones',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sensor_Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('operarios', models.ManyToManyField(blank=True, help_text='Seleccione los investigadores', null=True, to='api.Investigador')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sensor_Estacion')),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
