# Generated by Django 2.2.10 on 2021-02-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_componente_salidas_de_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_salida_de_campo',
            name='color2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
