# Generated by Django 2.2.10 on 2021-02-23 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_tipo_salida_de_campo_requerimientos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario_Salidas_De_Campo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, max_length=2000, null=True)),
                ('observaciones', models.TextField(blank=True, max_length=100000, null=True)),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion')),
                ('operarios', models.ManyToManyField(blank=True, help_text='Seleccione los investigadores', null=True, to='api.Investigador')),
                ('tipo_de_salida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Salida_De_Campo')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
