# Generated by Django 2.2.10 on 2021-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_calendario_salidas_de_campo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendario_salidas_de_campo',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.RenameField(
            model_name='calendario_salidas_de_campo',
            old_name='fecha',
            new_name='fecha_fin',
        ),
        migrations.AddField(
            model_name='calendario_salidas_de_campo',
            name='fecha_inicio',
            field=models.DateField(blank=True, max_length=2000, null=True),
        ),
    ]
