# Generated by Django 2.2.10 on 2021-02-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210224_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario_salidas_de_campo',
            name='operarios',
        ),
    ]
