# Generated by Django 2.2.10 on 2021-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_calendario_salidas_de_campo_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario_salidas_de_campo',
            name='color',
        ),
        migrations.AddField(
            model_name='estacion',
            name='color',
            field=models.CharField(blank=True, help_text='Ingrese el color en formato Hexa', max_length=200, null=True),
        ),
    ]
