# Generated by Django 2.2.10 on 2021-03-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210226_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_estacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(help_text='Ingrese el tipo de estación', max_length=200)),
                ('simbolo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria_sensor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipo_estacion'),
        ),
    ]
