# Generated by Django 2.2.10 on 2021-04-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20210405_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Estacion'),
        ),
        migrations.CreateModel(
            name='Codigo_Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sensor', models.CharField(max_length=10)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Componente_Estacion')),
                ('estacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Estacion')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Sensor_Estacion')),
            ],
        ),
    ]
