# Generated by Django 2.2.10 on 2021-04-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210410_0211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='variable',
            new_name='sensor',
        ),
        migrations.AlterField(
            model_name='estacion',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tipo_Estacion'),
        ),
    ]
